### ISSUE TITLE
import error "Calling function 'makeDecorator', function calls are not supported"

### ISSUE THREAD

**Issue by infinitysky** [uttesh/ng2letteravatar#1]
Hi all,
I meet some problem with this plugin.

Here is my running environment:
```

@angular/cli: 1.0.0-rc.1
node: 6.9.4
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
```

And  this the error message
```
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Component in C:/Users/xxx/Desktop/WorkingProjects/neutrino/ng2frontend/node_modules/ng2letteravatar/node_modules/@angular/core/src/metadata/directives.d.ts, resolving symbol Component in C:/Users/xxx/Desktop/WorkingProjects/neutrino/ng2frontend/node_modules/ng2letteravatar/node_modules/@angular/core/src/metadata.d.ts, resolving symbol Component in C:/Users/xxx/Desktop/WorkingProjects/neutrino/ng2frontend/node_modules/ng2letteravatar/node_modules/@angular/core/src/core.d.ts, resolving symbol Component in C:/Users/xxx/Desktop/WorkingProjects/neutrino/ng2frontend/node_modules/ng2letteravatar/node_modules/@angular/core/index.d.ts, resolving symbol Ng2LetterAvatar in C:/Users/xxx/Desktop/WorkingProjects/neutrino/ng2frontend/node_modules/ng2letteravatar/ng2letteravatar.ts, resolving symbol Ng2LetterAvatar in C:/Users/xxx/Desktop/WorkingProjects/neutrino/ng2frontend/node_modules/ng2letteravatar/ng2letteravatar.ts

```

**Comment by gastonelhordoy** [comment]
I'm facing the same error when building for production with angular-cli. `ng server` works well, but `ng build` doesn't.

**Comment by gastonelhordoy** [comment]
@infinitysky have you found any workaround?

**Comment by bendg25** [comment]
I am getting this issue to:

ERROR in Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/bengill/dev/flo/runtime-ui/node_modules/ng2letteravatar/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in /Users/bengill/dev/flo/runtime-ui/node_modules/ng2letteravatar/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in /Users/bengill/dev/flo/runtime-ui/node_modules/ng2letteravatar/node_modules/@angular/core/src/di/opaque_token.d.ts

Is this going to get fixed? If not, I am going to have to switch libraries.  Please advise.

**Comment by uttesh** [comment]
@infinitysky @gastonelhordoy @bendg25 

This component is moved to ngu-utility module https://github.com/uttesh/ngu-utility and all issues are addressed.
