### ISSUE TITLE
throwing following errors while 'npm start'

### ISSUE THREAD

**Issue by pgupta-infoobjects** [uttesh/ng2letteravatar#3]
node_modules/ng2letteravatar/ng2letteravatar.ts(162,13): error TS7005: Variable 'colorIndex' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(182,13): error TS7005: Variable 'component' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(235,23): error TS7006: Parameter 'width' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(235,30): error TS7006: Parameter 'height' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(235,38): error TS7006: Parameter 'color' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(235,45): error TS7006: Parameter 'cobj' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(260,33): error TS7006: Parameter 'character' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(260,44): error TS7006: Parameter 'textColor' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(260,55): error TS7006: Parameter 'fontFamily' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(260,67): error TS7006: Parameter 'fontWeight' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(260,79): error TS7006: Parameter 'fontsize' implicitly has an 'any' type.
node_modules/ng2letteravatar/ng2letteravatar.ts(303,30): error TS7006: Parameter 'data' implicitly has an 'any' type.

**Comment by pgupta-infoobjects** [comment]
@uttesh can you fix this as well ?

**Comment by uttesh** [comment]
@pgupta-infoobjects  please provide more details.

**Comment by pgupta-infoobjects** [comment]
@uttesh - I am using this with typescript and every time i do "npm start" to start the project it throw me mentioned error. TypeScript 2.0 it work on noImplicitAny as we have to define type of variables we are using. I have already sent you merge request with all the fix. Can you review it. 
for more details around "noImplicitAny", please follow this [link](https://basarat.gitbooks.io/typescript/docs/options/noImplicitAny.html)

**Comment by pgupta-infoobjects** [comment]
@uttesh - awaiting for the fix. Please can you review it.

**Comment by uttesh** [comment]
@pgupta-infoobjects 

This component is moved to ngu-utility module https://github.com/uttesh/ngu-utility and all issues are addressed.
