### ISSUE TITLE
this.letteravatar.clear() is not a function in ng2letteravatar.js

### ISSUE THREAD

**Issue by pgupta-infoobjects** [uttesh/ng2letteravatar#4]
Ng2LetterAvatar.prototype.ngOnDestroy = function () {
    if (this.letteravatar) {
        **this.letteravatar.clear();**
    }
};

**Comment by gastonelhordoy** [comment]
Same issue here, @uttesh do you mind having a look into it?

Tested with angular@2.4.9

**Comment by uttesh** [comment]
@gastonelhordoy  sorry for the late reply, will update the component this weekend.

**Comment by gastonelhordoy** [comment]
Sure thing, thank you for sharing your work @uttesh !

**Comment by infinitysky** [comment]
Hi sir,
This plugin works fine with angular 4. However, I still got the error message `this.letteravatar.clear is not a function`. Can you help us to check it please?
Thanks for your time and help
@uttesh

**Comment by uttesh** [comment]
@pgupta-infoobjects @gastonelhordoy @infinitysky  added the fix, please take the latest version.
Thanks

**Comment by uttesh** [comment]
@pgupta-infoobjects @gastonelhordoy @infinitysky 

This component is moved to ngu-utility module https://github.com/uttesh/ngu-utility and all issues are addressed.
