### ISSUE TITLE
Can I use this with Nativescript?

### ISSUE THREAD

**Issue by shiamalon** [uttesh/ng2letteravatar#6]
Hi @uttesh ,

I'm developing an app with Nativescript + Angular. Do you know if I can use your plugin?

Regards,

**Comment by uttesh-rivet** [comment]
@shiamalon sure, if any issues please report. thanks

**Comment by uttesh** [comment]
@shiamalon 
This component is moved to ngu-utility module https://github.com/uttesh/ngu-utility and all issues are addressed.
