### ISSUE TITLE
Unexpected value 'Ng2LetterAvatar' imported by the module 'AppModule' 

### ISSUE THREAD

**Issue by kanak-infoObjects** [uttesh/ng2letteravatar#8]
Hello Uttesh,
I am using this with Ionic 2 and when I build it using ionic build android --prod, I get the following errors.

> [19:47:31]  ionic-app-scripts 1.0.0 
> [19:47:31]  build prod started ... 
> [19:47:31]  clean started ... 
> [19:47:31]  clean finished in 1 ms 
> [19:47:31]  copy started ... 
> [19:47:31]  ngc started ... 
> [19:47:33]  build prod failed: Unexpected value 'Ng2LetterAvatar' imported by the module 'AppModule' 
> [19:47:33]  ionic-app-script task: "build" 
> [19:47:33]  Error: Unexpected value 'Ng2LetterAvatar' imported by the module 'AppModule' 
> Error: Unexpected value 'Ng2LetterAvatar' imported by the module 'AppModule'
>     at /home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:14675:33
>     at Array.forEach (native)
>     at CompileMetadataResolver._loadNgModuleMetadata (/home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
>     at CompileMetadataResolver.getUnloadedNgModuleMetadata (/home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
>     at addNgModule (/home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
>     at /home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
>     at Array.forEach (native)
>     at _createNgModules (/home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
>     at analyzeNgModules (/home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
>     at analyzeAndValidateNgModules (/home/infoobjects/Projects/truchat-mobile-2/truchat-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)

I have followed the steps given in the quickstart.

**Comment by kanak-infoObjects** [comment]
Can you please look into this? @uttesh 
Thanks in advance.

**Comment by uttesh** [comment]
@kanak-infoObjects i will look into it. are you using system.config.js?

**Comment by kanak-infoObjects** [comment]
@uttesh Yes I am using systemjs.config.js.

**Comment by uttesh** [comment]
@kanak-infoObjects is ng2letteravagtar load reference is there in that file?

**Comment by kanak-infoObjects** [comment]
> // See also: https://angular.io/docs/ts/latest/quickstart.html
> (function (global) {
>     // map tells the System loader where to look for things
>     var map = {
>         'app': 'app',
>         'rxjs': 'node_modules/rxjs',
>         '@angular': 'node_modules/@angular',
>         'ng2LAjs': 'node_modules/ng2letteravatar'
>     };
> 
>     // packages tells the System loader how to load when no filename and/or no extension
>     var packages = {
>         'rxjs': {defaultExtension: 'js'},
>         'ng2LAjs': {main: 'ng2LAjs/ng2letteravatar.js'},
>     };
> 
>     var angularPackages = [
>         'core',
>         'common',
>         'compiler',
>         'platform-browser',
>         'platform-browser-dynamic',
>         'http',
>         'router',
>         'forms',
>         'upgrade'
>     ];
> 
>     // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
>     angularPackages.forEach(function (pkgName) {
>         packages['@angular/' + pkgName] = {
>             main: 'bundles/' + pkgName + '.umd.js',
>             defaultExtension: 'js'
>         };
>     });
> 
>     var config = {
>         map: map,
>         packages: packages
>     }
> 
>     // filterSystemConfig - index.html's chance to modify config before we register it.
>     if (global.filterSystemConfig) {
>         global.filterSystemConfig(config);
>     }
> 
>     System.config(config);
> 
> })(this);

@uttesh This is how my systemjs.config.js file looks.

**Comment by aliasbody** [comment]
I don't know if this can help, but I had exactly the same problem and downgrading angular-cli to 1.0.2 was the solution, but it needs to be fixed.

**Comment by uttesh** [comment]
@kanak-infoObjects @aliasbody 

This component is moved to ngu-utility module https://github.com/uttesh/ngu-utility and all issues are addressed.
